name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.version }}
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mock pytest-cov setuptools
          python setup.py install
          pytest --cov=./ --cov-report=xml
      - name: Run Tests
        run: python -m pytest -v
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192 # v1.5.2
        with:
          name: codecov-umbrella
          fail_ci_if_error: false
